### ISSUE TITLE
TextInput not working on the TextBox

### ISSUE THREAD

**Issue by Edgarianom1212** [maxkatz6/AvaloniaHwndHostSample#1]
Hey @maxkatz6 

I just tried opening a avalonia window inside a rather big wpf application. The avalonia window opens just fine and any button presses on the avalonia window do work, but the textbox in the window does not receive any keyboard inputs. However if I paste some text into the textbox, the text is set inside the textbox, the return, delete key also work just fine, same as shortcuts like ctrl+a. 

The only thing not working is the normal keyboard inputs.

**Comment by maxkatz6** [comment]
I think there was a similar problem with winforms, which was fixed in 11.2 Avalonia builds. Can you try that?

**Comment by Edgarianom1212** [comment]
Thank you for the quick reply. I Just upgraded to the newest Avalonia build, but the error still persists. However I just found out, when I open the wpf window which has the avalonia control inside with the StartupUri in the app.xaml.cs, the textinput works just fine.

When I open my main window with the Program.cs manually, the avalonia control inside my main window, aswell as the previously opened wpf window via StartupUri dont accept text input anymore
